---
language: go

sudo: false

addons:
  apt:
    packages:
      # hammer
      - rpm

cache:
  directories:
    - .build-info

install:
  # packages for packaging
  - go get -v github.com/asteris-llc/hammer
  - gem install fpm
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr

script:
  - ./scripts/travis.sh

after_failure:
  - tail logs/*

after_success:
  - ghr --username prudhvitella --token $GITHUB_TOKEN --replace --prerelease --debug pre-release  /tmp/out/
branches:
  only:
    - master
